#!/usr/bin/env bash
# Visible build steps (for terminal / LaTeX Workshop single-tool recipe).
set -euo pipefail
ROOT="${1:?Pass jobname without .tex, e.g.: ./build.sh paper}"
cd "$(dirname "$0")"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  [1/4]  pdflatex  (first pass)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
pdflatex -synctex=1 -interaction=nonstopmode -file-line-error "$ROOT"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  [2/4]  bibtex"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bibtex "$ROOT"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  [3/4]  pdflatex  (resolve citations)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
pdflatex -synctex=1 -interaction=nonstopmode -file-line-error "$ROOT"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  [4/4]  pdflatex  (final)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
pdflatex -synctex=1 -interaction=nonstopmode -file-line-error "$ROOT"
echo ""
echo "✓ Done: $(pwd)/${ROOT}.pdf"
echo ""
